// components/AnalysisResults.tsx
"use client";
import { useState } from "react";
import type { TradingXbertAnalysis } from "@/lib/tradingTypes";

interface AnalysisResultsProps {
  analysis: TradingXbertAnalysis;
  onReset: () => void;
}

export default function AnalysisResults({ analysis, onReset }: AnalysisResultsProps) {
  const [copied, setCopied] = useState(false);
  const [saved, setSaved] = useState(false);

  const handleCopy = async () => {
    const summary = `
🚀 TradingXbert Analysis
═══════════════════════

📊 SIGNAL: ${analysis.signal} (${analysis.confidence}% confidence)
⚠️ RISK LEVEL: ${analysis.riskLevel}

📈 TREND & STRUCTURE:
${analysis.trendSummary}

🔍 PATTERN SUMMARY:
${analysis.patternSummary}

🎯 KEY LEVELS:
${analysis.keyLevels}

💡 STYLE NOTES:
${analysis.styleNotes}

${analysis.emotionSummary ? `🧠 EMOTION CHECK:\n${analysis.emotionSummary}\n\n` : ""}
${analysis.riskPlan ? `💰 RISK PLAN:\n${analysis.riskPlan}\n\n` : ""}
🎓 TEACH ME THIS SETUP:
${analysis.teachingTips}

Generated by TradingXbert.com 🤖✨
    `.trim();

    try {
      await navigator.clipboard.writeText(summary);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error("Failed to copy:", err);
    }
  };

  const handleShare = async () => {
    const url = typeof window !== "undefined" ? window.location.href : "";
    const text = `Check out my ${analysis.signal} trade analysis with ${analysis.confidence}% confidence! 📊`;

    if (navigator.share) {
      try {
        await navigator.share({
          title: "TradingXbert Analysis",
          text,
          url,
        });
      } catch (err) {
        // User cancelled
      }
    } else {
      // Fallback to Twitter
      const twitterUrl = `https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}&url=${encodeURIComponent(url)}`;
      window.open(twitterUrl, "_blank");
    }
  };

  const handleSaveToJournal = () => {
    // TODO: Implement journal save functionality
    setSaved(true);
    setTimeout(() => setSaved(false), 2000);
    alert("Journal feature coming soon! For now, use Copy Summary to save your analysis.");
  };

  const signalColors = {
    LONG: "from-emerald-500/30 via-emerald-600/20 to-emerald-700/10 border-emerald-400/60 text-emerald-300 shadow-emerald-500/20",
    SHORT: "from-red-500/30 via-red-600/20 to-red-700/10 border-red-400/60 text-red-300 shadow-red-500/20",
    WAIT: "from-amber-500/30 via-yellow-600/20 to-orange-700/10 border-yellow-400/60 text-yellow-300 shadow-yellow-500/20",
  };

  const signalEmoji = {
    LONG: "🚀",
    SHORT: "📉",
    WAIT: "⏸️",
  };

  const riskColors = {
    LOW: "text-emerald-400 bg-emerald-500/10 border-emerald-500/30",
    MEDIUM: "text-yellow-400 bg-yellow-500/10 border-yellow-500/30",
    HIGH: "text-red-400 bg-red-500/10 border-red-500/30",
  };

  return (
    <div className="w-full max-w-5xl mx-auto animate-in fade-in-0 zoom-in-95 duration-500">
      {/* Epic Signal Hero Card with Gold Accents */}
      <div className={`relative rounded-3xl border-2 p-10 mb-8 bg-gradient-to-br ${signalColors[analysis.signal]} shadow-2xl overflow-hidden`}>
        {/* Animated Background */}
        <div className="absolute inset-0 bg-gradient-to-r from-[#FFD700]/5 via-transparent to-[#FFA500]/5 animate-pulse" />
        
        <div className="relative z-10 text-center">
          <div className="text-8xl mb-4 animate-bounce">{signalEmoji[analysis.signal]}</div>
          <div className="text-7xl font-black mb-3 tracking-tight drop-shadow-lg">{analysis.signal}</div>
          <div className="text-3xl font-bold mb-4">{analysis.confidence}% Confidence</div>
          
          {/* Confidence Meter with Gold */}
          <div className="w-full max-w-md mx-auto bg-white/10 rounded-full h-4 overflow-hidden backdrop-blur-sm border border-white/20">
            <div 
              className="h-full bg-gradient-to-r from-[#FFD700] via-[#FFA500] to-[#FF8C00] rounded-full transition-all duration-1000 ease-out shadow-lg shadow-[#FFD700]/50"
              style={{ width: `${analysis.confidence}%` }}
            />
          </div>
          
          {/* Smart Money Badge */}
          <div className="mt-6 inline-flex items-center gap-2 px-6 py-3 bg-gradient-to-r from-[#FFD700]/20 to-[#FFA500]/20 border border-[#FFD700]/40 rounded-full backdrop-blur-sm">
            <span className="text-2xl">⚖️</span>
            <span className="font-bold text-[#FFD700]">Smart Money Analysis</span>
          </div>
        </div>
      </div>

      {/* Main Analysis Grid */}
      <div className="grid md:grid-cols-2 gap-6 mb-8">
        {/* Trend & Structure */}
        <AnalysisCard title="Trend & Structure" icon="📊" iconGradient="from-blue-400 to-cyan-400">
          <p className="text-neutral-200 leading-relaxed text-lg">{analysis.trendSummary}</p>
        </AnalysisCard>

        {/* Pattern Summary */}
        <AnalysisCard title="Pattern Summary" icon="🔍" iconGradient="from-purple-400 to-pink-400">
          <p className="text-neutral-200 leading-relaxed text-lg">{analysis.patternSummary}</p>
        </AnalysisCard>

        {/* Key Levels */}
        <AnalysisCard title="Key Levels" icon="🎯" iconGradient="from-red-400 to-orange-400">
          <p className="text-neutral-200 leading-relaxed text-lg whitespace-pre-line font-mono">{analysis.keyLevels}</p>
        </AnalysisCard>

        {/* Risk Level */}
        <AnalysisCard title="Risk Assessment" icon="⚠️" iconGradient="from-yellow-400 to-amber-400">
          <div className={`inline-flex px-6 py-3 rounded-xl border-2 ${riskColors[analysis.riskLevel]}`}>
            <p className="text-3xl font-black">
              {analysis.riskLevel} RISK
            </p>
          </div>
        </AnalysisCard>
      </div>

      {/* Full Width Cards */}
      <div className="space-y-6 mb-8">
        {/* Style Notes */}
        <AnalysisCard title="Trading Strategy" icon="💡" iconGradient="from-emerald-400 to-green-400" fullWidth>
          <p className="text-neutral-200 leading-relaxed text-lg">{analysis.styleNotes}</p>
        </AnalysisCard>

        {/* Emotion Check */}
        {analysis.emotionSummary && (
          <AnalysisCard title="Psychology Check" icon="🧠" iconGradient="from-indigo-400 to-purple-400" fullWidth>
            <p className="text-neutral-200 leading-relaxed text-lg italic">{analysis.emotionSummary}</p>
          </AnalysisCard>
        )}

        {/* Risk Plan */}
        {analysis.riskPlan && (
          <AnalysisCard title="Risk Management Plan" icon="💰" iconGradient="from-[#FFD700] to-[#FFA500]" fullWidth>
            <p className="text-neutral-200 leading-relaxed text-lg font-semibold">{analysis.riskPlan}</p>
          </AnalysisCard>
        )}

        {/* Teaching Tips - Make it POP */}
        <div className="relative bg-gradient-to-br from-[#FFD700]/10 via-[#FFA500]/5 to-transparent backdrop-blur-xl rounded-3xl border-2 border-[#FFD700]/30 p-8 shadow-2xl shadow-[#FFD700]/10">
          <div className="absolute top-0 left-0 w-32 h-32 bg-[#FFD700]/10 rounded-full blur-3xl -z-10" />
          <div className="absolute bottom-0 right-0 w-32 h-32 bg-[#FFA500]/10 rounded-full blur-3xl -z-10" />
          
          <div className="flex items-center gap-3 mb-6">
            <span className="text-5xl">🎓</span>
            <h3 className="text-3xl font-black text-transparent bg-clip-text bg-gradient-to-r from-[#FFD700] to-[#FFA500]">
              Master This Setup
            </h3>
          </div>
          <div className="text-neutral-200 leading-relaxed text-lg whitespace-pre-line space-y-3">
            {analysis.teachingTips.split('\n').map((tip, i) => (
              <div key={i} className="flex items-start gap-3 p-3 bg-white/5 rounded-xl hover:bg-white/10 transition-colors">
                <span className="text-[#FFD700] text-xl">💎</span>
                <span>{tip}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Confidence Breakdown */}
        {analysis.confidenceBreakdown && (
          <AnalysisCard title="Confidence Breakdown" icon="📈" iconGradient="from-teal-400 to-cyan-400" fullWidth>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
              {Object.entries(analysis.confidenceBreakdown).map(([key, value]) => (
                <div key={key} className="text-center p-4 bg-white/5 rounded-xl border border-white/10 hover:border-[#FFD700]/50 transition-all hover:scale-105">
                  <div className="text-sm text-neutral-400 uppercase tracking-wider mb-2">{key}</div>
                  <div className="text-3xl font-bold text-[#FFD700]">{value}%</div>
                  <div className="mt-2 w-full bg-white/10 rounded-full h-2">
                    <div 
                      className="h-full bg-gradient-to-r from-[#FFD700] to-[#FFA500] rounded-full"
                      style={{ width: `${value}%` }}
                    />
                  </div>
                </div>
              ))}
            </div>
          </AnalysisCard>
        )}
      </div>

      {/* Epic Action Buttons */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <button
          onClick={onReset}
          className="group relative bg-gradient-to-r from-[#6366F1] to-[#8B5CF6] hover:from-[#5558E3] hover:to-[#7C3AED] text-white font-bold py-5 px-6 rounded-2xl transition-all duration-300 shadow-lg hover:shadow-2xl hover:shadow-[#6366F1]/50 hover:scale-105"
        >
          <span className="flex items-center justify-center gap-2 text-lg">
            🔄 New Analysis
          </span>
        </button>
        
        <button
          onClick={handleCopy}
          className="group relative bg-gradient-to-r from-[#FFD700]/20 to-[#FFA500]/20 hover:from-[#FFD700]/30 hover:to-[#FFA500]/30 border-2 border-[#FFD700]/50 hover:border-[#FFD700] text-[#FFD700] font-bold py-5 px-6 rounded-2xl transition-all duration-300 shadow-lg hover:shadow-2xl hover:shadow-[#FFD700]/30 hover:scale-105"
        >
          <span className="flex items-center justify-center gap-2 text-lg">
            {copied ? "✓ Copied!" : "📋 Copy Summary"}
          </span>
        </button>
        
        <button
          onClick={handleShare}
          className="group relative bg-white/5 hover:bg-white/10 border-2 border-white/20 hover:border-[#FFD700]/50 text-white hover:text-[#FFD700] font-bold py-5 px-6 rounded-2xl transition-all duration-300 shadow-lg hover:shadow-2xl hover:scale-105"
        >
          <span className="flex items-center justify-center gap-2 text-lg">
            🚀 Share
          </span>
        </button>
        
        <button
          onClick={handleSaveToJournal}
          className="group relative bg-gradient-to-r from-emerald-500/20 to-green-500/20 hover:from-emerald-500/30 hover:to-green-500/30 border-2 border-emerald-500/50 hover:border-emerald-400 text-emerald-400 font-bold py-5 px-6 rounded-2xl transition-all duration-300 shadow-lg hover:shadow-2xl hover:shadow-emerald-500/30 hover:scale-105"
        >
          <span className="flex items-center justify-center gap-2 text-lg">
            {saved ? "✓ Saved!" : "💾 Save to Journal"}
          </span>
        </button>
      </div>
    </div>
  );
}

function AnalysisCard({ 
  title, 
  icon, 
  iconGradient, 
  children, 
  fullWidth = false 
}: { 
  title: string; 
  icon: string; 
  iconGradient: string;
  children: React.ReactNode;
  fullWidth?: boolean;
}) {
  return (
    <div className={`relative bg-gradient-to-br from-white/10 via-white/5 to-transparent backdrop-blur-xl rounded-3xl border border-white/20 hover:border-[#FFD700]/30 p-8 shadow-xl hover:shadow-2xl transition-all duration-300 hover:scale-[1.02] ${fullWidth ? 'col-span-full' : ''}`}>
      <div className="flex items-center gap-4 mb-6">
        <div className={`text-5xl p-4 rounded-2xl bg-gradient-to-br ${iconGradient} bg-opacity-10 shadow-lg`}>
          {icon}
        </div>
        <h3 className="text-2xl font-black text-white">
          {title}
        </h3>
      </div>
      <div className="relative z-10">
        {children}
      </div>
    </div>
  );
}
