// components/AnalysisResults.tsx
"use client";
import { useState } from "react";
import type { TradingXbertAnalysis } from "@/lib/tradingTypes";

interface AnalysisResultsProps {
  analysis: TradingXbertAnalysis;
  onReset: () => void;
}

export default function AnalysisResults({ analysis, onReset }: AnalysisResultsProps) {
  const [copied, setCopied] = useState(false);
  const [saved, setSaved] = useState(false);

  const handleCopy = async () => {
    const summary = `
🚀 TradingXbert Analysis
═══════════════════════

📊 SIGNAL: ${analysis.signal} (${analysis.confidence}% confidence)
⚠️ RISK LEVEL: ${analysis.riskLevel}

📈 TREND & STRUCTURE:
${analysis.trendSummary}

🔍 PATTERN SUMMARY:
${analysis.patternSummary}

🎯 KEY LEVELS:
${analysis.keyLevels}

💡 STYLE NOTES:
${analysis.styleNotes}

${analysis.emotionSummary ? `🧠 EMOTION CHECK:\n${analysis.emotionSummary}\n\n` : ""}
${analysis.riskPlan ? `💰 RISK PLAN:\n${analysis.riskPlan}\n\n` : ""}
🎓 TEACH ME THIS SETUP:
${analysis.teachingTips}

Generated by TradingXbert.com 🤖✨
    `.trim();

    try {
      await navigator.clipboard.writeText(summary);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error("Failed to copy:", err);
    }
  };

  const handleShare = async () => {
    const url = typeof window !== "undefined" ? window.location.href : "";
    const text = `Check out my ${analysis.signal} trade analysis with ${analysis.confidence}% confidence! 📊`;

    if (navigator.share) {
      try {
        await navigator.share({
          title: "TradingXbert Analysis",
          text,
          url,
        });
      } catch (err) {
        // User cancelled
      }
    } else {
      // Fallback to Twitter
      const twitterUrl = `https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}&url=${encodeURIComponent(url)}`;
      window.open(twitterUrl, "_blank");
    }
  };

  const handleSaveToJournal = () => {
    // Analyses are auto-saved to profile when logged in
    setSaved(true);
    setTimeout(() => setSaved(false), 2000);
  };

  const signalColors = {
    LONG: "from-emerald-500/30 via-emerald-600/20 to-emerald-700/10 border-emerald-400/60 text-emerald-300 shadow-emerald-500/20",
    SHORT: "from-red-500/30 via-red-600/20 to-red-700/10 border-red-400/60 text-red-300 shadow-red-500/20",
    WAIT: "from-amber-500/30 via-yellow-600/20 to-orange-700/10 border-yellow-400/60 text-yellow-300 shadow-yellow-500/20",
  };

  const signalEmoji = {
    LONG: "🚀",
    SHORT: "📉",
    WAIT: "⏸️",
  };

  const riskColors = {
    LOW: "text-emerald-400 bg-emerald-500/10 border-emerald-500/30",
    MEDIUM: "text-yellow-400 bg-yellow-500/10 border-yellow-500/30",
    HIGH: "text-red-400 bg-red-500/10 border-red-500/30",
  };

  return (
    <div className="w-full max-w-7xl mx-auto animate-in fade-in-0 zoom-in-95 duration-500">
      {/* Epic Signal Hero Card - COMPACT */}
      <div className={`relative rounded-2xl border-2 p-6 mb-6 bg-gradient-to-br ${signalColors[analysis.signal]} shadow-2xl overflow-hidden`}>
        {/* Animated Background */}
        <div className="absolute inset-0 bg-gradient-to-r from-[#FFD700]/5 via-transparent to-[#FFA500]/5 animate-pulse" />
        
        <div className="relative z-10 flex items-center justify-between flex-wrap gap-4">
          <div className="flex items-center gap-4">
            <div className="text-6xl animate-bounce">{signalEmoji[analysis.signal]}</div>
            <div>
              <div className="text-5xl font-black tracking-tight drop-shadow-lg">{analysis.signal}</div>
              <div className="text-xl font-bold text-neutral-300">{analysis.confidence}% Confidence</div>
            </div>
          </div>
          
          <div className="flex items-center gap-4">
            {/* Confidence Meter */}
            <div className="w-48 bg-white/10 rounded-full h-3 overflow-hidden backdrop-blur-sm border border-white/20">
              <div 
                className="h-full bg-gradient-to-r from-[#FFD700] via-[#FFA500] to-[#FF8C00] rounded-full transition-all duration-1000 ease-out shadow-lg shadow-[#FFD700]/50"
                style={{ width: `${analysis.confidence}%` }}
              />
            </div>
            
            {/* Risk Badge */}
            <div className={`px-4 py-2 rounded-xl border-2 font-bold ${riskColors[analysis.riskLevel]}`}>
              {analysis.riskLevel} RISK
            </div>
          </div>
        </div>
      </div>

      {/* TRADE SETUP - IF LONG/SHORT */}
      {(analysis.signal === "LONG" || analysis.signal === "SHORT") && (
        <div className="mb-6 relative bg-gradient-to-br from-[#FFD700]/20 via-[#FFA500]/10 to-transparent backdrop-blur-xl rounded-2xl border-2 border-[#FFD700] p-6 shadow-2xl">
          <div className="absolute top-0 left-0 w-32 h-32 bg-[#FFD700]/20 rounded-full blur-3xl -z-10" />
          <div className="absolute bottom-0 right-0 w-32 h-32 bg-[#FFA500]/20 rounded-full blur-3xl -z-10" />
          
          <div className="flex items-center gap-3 mb-4">
            <span className="text-4xl">🎯</span>
            <h2 className="text-3xl font-black text-transparent bg-clip-text bg-gradient-to-r from-[#FFD700] to-[#FFA500]">
              TRADE SETUP - {analysis.signal}
            </h2>
          </div>
          
          <div className="grid md:grid-cols-3 gap-4">
            {/* Entry Zone */}
            <div className="bg-white/10 backdrop-blur-sm rounded-xl p-4 border-2 border-blue-400/50 hover:border-blue-400 transition-all">
              <div className="flex items-center gap-2 mb-2">
                <span className="text-2xl">📍</span>
                <div className="text-sm font-bold text-blue-400 uppercase">Entry Zone</div>
              </div>
              <div className="text-2xl font-black text-white mb-1">
                {analysis.keyLevels.match(/Entry[:\s]+([^\n]+)/i)?.[1] || 
                 analysis.keyLevels.match(/Support[:\s]+([^\n]+)/i)?.[1] ||
                 "See Key Levels"}
              </div>
              <div className="text-xs text-neutral-400">
                {analysis.signal === "LONG" ? "Buy near support" : "Sell near resistance"}
              </div>
            </div>
            
            {/* Stop Loss */}
            <div className="bg-white/10 backdrop-blur-sm rounded-xl p-4 border-2 border-red-400/50 hover:border-red-400 transition-all">
              <div className="flex items-center gap-2 mb-2">
                <span className="text-2xl">🛑</span>
                <div className="text-sm font-bold text-red-400 uppercase">Stop Loss (SL)</div>
              </div>
              <div className="text-2xl font-black text-white mb-1">
                {analysis.keyLevels.match(/Stop[:\s]+([^\n]+)/i)?.[1] || 
                 analysis.keyLevels.match(/SL[:\s]+([^\n]+)/i)?.[1] ||
                 (analysis.signal === "LONG" ? "Below Support" : "Above Resistance")}
              </div>
              <div className="text-xs text-neutral-400">
                Exit if trade goes against you
              </div>
            </div>
            
            {/* Take Profit */}
            <div className="bg-white/10 backdrop-blur-sm rounded-xl p-4 border-2 border-emerald-400/50 hover:border-emerald-400 transition-all">
              <div className="flex items-center gap-2 mb-2">
                <span className="text-2xl">💰</span>
                <div className="text-sm font-bold text-emerald-400 uppercase">Take Profit (TP)</div>
              </div>
              <div className="text-2xl font-black text-white mb-1">
                {analysis.keyLevels.match(/Target[:\s]+([^\n]+)/i)?.[1] || 
                 analysis.keyLevels.match(/TP[:\s]+([^\n]+)/i)?.[1] ||
                 (analysis.signal === "LONG" ? "At Resistance" : "At Support")}
              </div>
              <div className="text-xs text-neutral-400">
                Take profits at target level
              </div>
            </div>
          </div>
          
          {/* Risk Management Summary */}
          {analysis.riskPlan && (
            <div className="mt-4 p-4 bg-gradient-to-r from-[#FFD700]/10 to-[#FFA500]/10 rounded-xl border border-[#FFD700]/30">
              <div className="flex items-start gap-2">
                <span className="text-xl">💎</span>
                <div>
                  <div className="font-bold text-[#FFD700] mb-1">Risk Management:</div>
                  <div className="text-sm text-neutral-200">{analysis.riskPlan}</div>
                </div>
              </div>
            </div>
          )}
          
          {/* Quick Action Summary */}
          <div className="mt-4 p-4 bg-black/20 rounded-xl border border-white/10">
            <div className="text-lg font-bold text-white mb-2">✅ Action Plan:</div>
            <ul className="space-y-1 text-sm text-neutral-300">
              <li>• {analysis.signal === "LONG" ? "Wait for price to reach entry zone (support)" : "Wait for price to reach entry zone (resistance)"}</li>
              <li>• Set your Stop Loss {analysis.signal === "LONG" ? "below support" : "above resistance"} to limit risk</li>
              <li>• Set your Take Profit at the target level</li>
              <li>• Use proper position sizing based on your risk tolerance ({analysis.riskLevel} risk setup)</li>
              <li>• Monitor for confirmation signals before entering</li>
            </ul>
          </div>
        </div>
      )}

      {/* Main Analysis Grid - MORE COMPACT */}
      <div className="grid md:grid-cols-3 gap-4 mb-6">
        {/* Trend & Structure */}
        <AnalysisCard title="Trend & Structure" icon="📊" iconGradient="from-blue-400 to-cyan-400" compact>
          <p className="text-neutral-200 leading-relaxed text-sm">{analysis.trendSummary}</p>
        </AnalysisCard>

        {/* Pattern Summary */}
        <AnalysisCard title="Pattern Summary" icon="🔍" iconGradient="from-purple-400 to-pink-400" compact>
          <p className="text-neutral-200 leading-relaxed text-sm">{analysis.patternSummary}</p>
        </AnalysisCard>

        {/* Key Levels */}
        <AnalysisCard title="Key Levels" icon="🎯" iconGradient="from-red-400 to-orange-400" compact>
          <p className="text-neutral-200 leading-relaxed text-sm whitespace-pre-line font-mono">{analysis.keyLevels}</p>
        </AnalysisCard>
      </div>

      {/* Full Width Cards - COMPACT */}
      <div className="space-y-4 mb-6">
        {/* Style Notes */}
        <AnalysisCard title="Trading Strategy" icon="💡" iconGradient="from-emerald-400 to-green-400" fullWidth compact>
          <p className="text-neutral-200 leading-relaxed text-sm">{analysis.styleNotes}</p>
        </AnalysisCard>

        {/* Emotion Check */}
        {analysis.emotionSummary && (
          <AnalysisCard title="Psychology Check" icon="🧠" iconGradient="from-indigo-400 to-purple-400" fullWidth compact>
            <p className="text-neutral-200 leading-relaxed text-sm italic">{analysis.emotionSummary}</p>
          </AnalysisCard>
        )}

        {/* Teaching Tips - Make it POP but COMPACT */}
        <div className="relative bg-gradient-to-br from-[#FFD700]/10 via-[#FFA500]/5 to-transparent backdrop-blur-xl rounded-2xl border-2 border-[#FFD700]/30 p-6 shadow-2xl shadow-[#FFD700]/10">
          <div className="absolute top-0 left-0 w-24 h-24 bg-[#FFD700]/10 rounded-full blur-3xl -z-10" />
          <div className="absolute bottom-0 right-0 w-24 h-24 bg-[#FFA500]/10 rounded-full blur-3xl -z-10" />
          
          <div className="flex items-center gap-3 mb-4">
            <span className="text-3xl">🎓</span>
            <h3 className="text-2xl font-black text-transparent bg-clip-text bg-gradient-to-r from-[#FFD700] to-[#FFA500]">
              Master This Setup
            </h3>
          </div>
          <div className="text-neutral-200 leading-relaxed text-sm space-y-2">
            {(typeof analysis.teachingTips === 'string' ? analysis.teachingTips : String(analysis.teachingTips || '')).split('\n').filter(tip => tip.trim()).map((tip, i) => (
              <div key={i} className="flex items-start gap-2 p-2 bg-white/5 rounded-lg hover:bg-white/10 transition-colors">
                <span className="text-[#FFD700] text-lg flex-shrink-0">💎</span>
                <span className="text-sm">{tip}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Confidence Breakdown - COMPACT */}
        {analysis.confidenceBreakdown && (
          <AnalysisCard title="Confidence Breakdown" icon="📈" iconGradient="from-teal-400 to-cyan-400" fullWidth compact>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
              {Object.entries(analysis.confidenceBreakdown).map(([key, value]) => (
                <div key={key} className="text-center p-3 bg-white/5 rounded-xl border border-white/10 hover:border-[#FFD700]/50 transition-all hover:scale-105">
                  <div className="text-xs text-neutral-400 uppercase tracking-wider mb-1">{key}</div>
                  <div className="text-2xl font-bold text-[#FFD700]">{value}%</div>
                  <div className="mt-1 w-full bg-white/10 rounded-full h-1.5">
                    <div 
                      className="h-full bg-gradient-to-r from-[#FFD700] to-[#FFA500] rounded-full"
                      style={{ width: `${value}%` }}
                    />
                  </div>
                </div>
              ))}
            </div>
          </AnalysisCard>
        )}
      </div>

      {/* Epic Action Buttons - COMPACT */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">
        <button
          onClick={onReset}
          className="group relative bg-gradient-to-r from-[#6366F1] to-[#8B5CF6] hover:from-[#5558E3] hover:to-[#7C3AED] text-white font-bold py-4 px-4 rounded-xl transition-all duration-300 shadow-lg hover:shadow-2xl hover:shadow-[#6366F1]/50 hover:scale-105"
        >
          <span className="flex items-center justify-center gap-2">
            🔄 New Analysis
          </span>
        </button>
        
        <button
          onClick={handleCopy}
          className="group relative bg-gradient-to-r from-[#FFD700]/20 to-[#FFA500]/20 hover:from-[#FFD700]/30 hover:to-[#FFA500]/30 border-2 border-[#FFD700]/50 hover:border-[#FFD700] text-[#FFD700] font-bold py-4 px-4 rounded-xl transition-all duration-300 shadow-lg hover:shadow-2xl hover:shadow-[#FFD700]/30 hover:scale-105"
        >
          <span className="flex items-center justify-center gap-2">
            {copied ? "✓ Copied!" : "📋 Copy"}
          </span>
        </button>
        
        <button
          onClick={handleShare}
          className="group relative bg-white/5 hover:bg-white/10 border-2 border-white/20 hover:border-[#FFD700]/50 text-white hover:text-[#FFD700] font-bold py-4 px-4 rounded-xl transition-all duration-300 shadow-lg hover:shadow-2xl hover:scale-105"
        >
          <span className="flex items-center justify-center gap-2">
            🚀 Share
          </span>
        </button>
        
        <button
          onClick={handleSaveToJournal}
          className="group relative bg-gradient-to-r from-emerald-500/20 to-green-500/20 hover:from-emerald-500/30 hover:to-green-500/30 border-2 border-emerald-500/50 hover:border-emerald-400 text-emerald-400 font-bold py-4 px-4 rounded-xl transition-all duration-300 shadow-lg hover:shadow-2xl hover:shadow-emerald-500/30 hover:scale-105"
        >
          <span className="flex items-center justify-center gap-2">
            {saved ? "✓ Saved!" : "💾 Save"}
          </span>
        </button>
      </div>
    </div>
  );
}

function AnalysisCard({ 
  title, 
  icon, 
  iconGradient, 
  children, 
  fullWidth = false,
  compact = false
}: { 
  title: string; 
  icon: string; 
  iconGradient: string;
  children: React.ReactNode;
  fullWidth?: boolean;
  compact?: boolean;
}) {
  return (
    <div className={`relative bg-gradient-to-br from-white/10 via-white/5 to-transparent backdrop-blur-xl rounded-2xl border border-white/20 hover:border-[#FFD700]/30 ${compact ? 'p-4' : 'p-8'} shadow-xl hover:shadow-2xl transition-all duration-300 hover:scale-[1.02] ${fullWidth ? 'col-span-full' : ''}`}>
      <div className={`flex items-center gap-3 ${compact ? 'mb-3' : 'mb-6'}`}>
        <div className={`${compact ? 'text-3xl p-2' : 'text-5xl p-4'} rounded-2xl bg-gradient-to-br ${iconGradient} bg-opacity-10 shadow-lg`}>
          {icon}
        </div>
        <h3 className={`${compact ? 'text-lg' : 'text-2xl'} font-black text-white`}>
          {title}
        </h3>
      </div>
      <div className="relative z-10">
        {children}
      </div>
    </div>
  );
}
