export const testimonials = [
  {
    id: 1,
    username: "Cr7pt0_Sn1p3r",
    avatar: "🎯",
    role: "Day Trader",
    text: "TradingXbert turned my trading around. The AI catches patterns I'd miss and saved me from 3 bad trades this week alone. Worth every penny.",
    rating: 5,
    verified: true,
  },
  {
    id: 2,
    username: "0xD3G3N_K1NG",
    avatar: "👑",
    role: "Futures Trader",
    text: "This AI is insane. Spotted a head & shoulders before I even noticed. Confidence scores are spot on. Made back my subscription in 2 trades.",
    rating: 5,
    verified: true,
  },
  {
    id: 3,
    username: "M00N_CH4S3R",
    avatar: "🚀",
    role: "Swing Trader",
    text: "Finally an AI that actually understands price action. The teaching tips helped me level up faster than any course. Legit game changer.",
    rating: 5,
    verified: true,
  },
  {
    id: 4,
    username: "V0L4T1L1TY_V1P3R",
    avatar: "⚡",
    role: "Scalper",
    text: "Been trading 4 years. This tool analyzes charts faster than I can and spots things I'd spend 30 min looking for. The risk levels are gold.",
    rating: 5,
    verified: true,
  },
  {
    id: 5,
    username: "BL0CKch41n_B4ND1T",
    avatar: "🏴‍☠️",
    role: "Options Trader",
    text: "Skeptical at first but damn... caught a reversal pattern that netted me 400%. The emotion check feature keeps me disciplined too.",
    rating: 5,
    verified: true,
  },
  {
    id: 6,
    username: "CYB3R_C4P1T4L",
    avatar: "💎",
    role: "Portfolio Manager",
    text: "Using this for my entire portfolio analysis now. The confidence breakdown is next level. Team loves the shareable reports.",
    rating: 5,
    verified: true,
  },
];
